apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  #storageClassName: hostpath
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-cm
data:
  app.env: |
    DJANGO_DEBUG=0
    ALLOWED_HOSTS=*
    READINESS_DELAY=10
  gunicorn.conf.py: |
    import os
    workers = 2
    threads = 2
    timeout = 60
    bind = f"0.0.0.0:{os.getenv('PORT', '8000')}"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  DB_USERNAME: myuser
  DB_PASSWORD: mysecurepassword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: django-app
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      volumes:
      - name: volume-pv
        persistentVolumeClaim: 
          claimName: pv-claim
      - name: volume-emptydir
        emptyDir:
          sizeLimit: 500Mi
      - name: volume-cm
        configMap:
          name: volume-cm
          items:
          - key: app.env
            path: app.env
          - key: gunicorn.conf.py
            path: gunicorn.conf.py
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: dharshil10/django-app:v6
        name: django-app-01
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080" 
        - name: GUNICORN_CMD_ARGS
          value: "-c /usr/src/app/configs/gunicorn.conf.py"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USERNAME
        - name: DB_PASSWORD  
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 8080
          name: port00
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: volume-pv
          mountPath: /usr/src/app/data
        - name: volume-emptydir
          mountPath: /usr/src/app/logs
        - name: volume-cm
          mountPath: /usr/src/app/configs
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        startupProbe:
          httpGet:
            path: /startup
            port: port00
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 10            
        livenessProbe:
          httpGet:
            path: /live
            port: port00
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: port00
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 10  
      - image: dharshil10/django-app:v6
        name: django-app-02
        # command: ["gunicorn"]
        # args: ["config.wsgi:application", "--bind", "0.0.0.0:8001"]
        env:
        - name: PORT
          value: "8081" 
        - name: GUNICORN_CMD_ARGS
          value: "-c /usr/src/app/configs/gunicorn.conf.py"
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: port01
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: volume-pv
          mountPath: /usr/src/app/data
        - name: volume-emptydir
          mountPath: /usr/src/app/logs
        - name: volume-cm
          mountPath: /usr/src/app/configs
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        startupProbe:
          httpGet:
            path: /startup
            port: port01
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 10            
        livenessProbe:
          httpGet:
            path: /live
            port: port01
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: port01
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata: 
  name: app-service-ci
spec:
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: port00
    name: http01
  - protocol: TCP
    port: 81
    targetPort: port01
    name: http02
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
  - host: django-app.andy-labs.us
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service-ci
            port:
              number: 80