apiVersion: v1
kind: Service
metadata:
  name: dj-k8s-practice
  labels:
    app: dj-k8s-practice
spec:
  selector:
    app: dj-k8s-practice
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
